#+title: Alien Dictionary

There is a new alien language that uses the English alphabet. However, the order among the letters is unknown to you.

You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new
language.

Return a string of the unique letters in the new alien language sorted in lexicographically increasing order by the new language's rules. If there is no
solution, return "". If there are multiple solutions, return any of them.

A string s is lexicographically smaller than a string t if at the first letter where they differ, the letter in s comes before the letter in t in the alien
language. If the first min(s.length, t.length) letters are the same, then s is smaller if and only if s.length < t.length.

* Topological sort

  Build a directed graph where an edge (u, v) means u is lexicographically smaller than v. Also keep the number of in-degrees for each node.
  Use a queue to keep track of all the nodes that's either with a in-degree 0 initially or become 0 later when removed all their predecessors.

  Two situations to return empty string:
  1. there's a cycle in the graph, specifically when the queue is empty but not all in-degrees are zero.
  2. Invalid input.
