#+title: Count All Possible Routes

You are given an array of distinct positive integers locations where locations[i] represents the position of city i. You are also given integers start, finish
and fuel representing the starting city, ending city, and the initial amount of fuel you have, respectively.

At each step, if you are at city i, you can pick any city j such that j != i and 0 <= j < locations.length and move to city j. Moving from city i to city j
reduces the amount of fuel you have by |locations[i] - locations[j]|. Please notice that |x| denotes the absolute value of x.

Notice that fuel cannot become negative at any point in time, and that you are allowed to visit any city more than once (including start and finish).

Return the count of all possible routes from start to finish. Since the answer may be too large, return it modulo 10^9 + 7.

* Solution

  Consider a function =F(fuel, loc)= that returns the number of different routes from start to loc with the given fuel. Note fuel do not have to be used up. Then we
  have the following observation about function F:

  1. =F(any fuel, start)= equals 1, from start to start always has one route no mater how much fuel you have.
  2. =F(fuel, loc)= equals the sum of =F(fuel - cost, j)= where j is any other location and cost is the cost from loc to j, provided it's not larger than fuel.
